CREATE TABLE [dbo].[TbMntUnitaIntrv] (
    [IdIntrv]         NVARCHAR (20)  NOT NULL,
    [BlocDoc]         BIT            NULL,
    [IdCausaleIntrv]  NVARCHAR (20)  NULL,
    [IdPiano]         INT            NULL,
    [IdProdLotto]     NVARCHAR (20)  NULL,
    [IdOdlDet]        INT            NULL,
    [IdUnita]         INT            NULL,
    [IdArticolo]      NVARCHAR (50)  NULL,
    [DataFermo]       DATETIME       NULL,
    [DataRicIntrv]    DATETIME       NULL,
    [DataIntrv]       DATETIME       NULL,
    [DataFineIntrv]   DATETIME       NULL,
    [DurataPrevIntrv] INT            NULL,
    [IdUtenteProd]    NVARCHAR (256) NULL,
    [IdUtenteIntrv]   NVARCHAR (256) NULL,
    [IdManutentore]   INT            NULL,
    [Manutentore]     NVARCHAR (200) NULL,
    [DescIntrv]       NVARCHAR (MAX) NULL,
    [NoteIntrv]       NVARCHAR (MAX) NULL,
    [CodFnzEsito]     NVARCHAR (5)   NULL,
    [Costo]           MONEY          NULL,
    [IdMage]          NVARCHAR (10)  NULL,
    [IdMage1]         NVARCHAR (10)  NULL,
    [MagePosiz]       NVARCHAR (20)  NULL,
    [MagePosiz1]      NVARCHAR (20)  NULL,
    [SysUserCreate]   NVARCHAR (256) NULL,
    [SysDateUpdate]   DATETIME       NULL,
    [SysUserUpdate]   NVARCHAR (256) NULL,
    [SysRowVersion]   ROWVERSION     NULL,
    [SysDateCreate]   DATETIME       CONSTRAINT [DF_TbMntUnitaIntrv_SysDateCreate] DEFAULT (getdate()) NULL,
    [DurataIntrv]     INT            NULL,
    [IdCdlunita]      NVARCHAR (20)  NULL,
    CONSTRAINT [PK_TbMntUnitaIntrv] PRIMARY KEY CLUSTERED ([IdIntrv] ASC),
    CONSTRAINT [FK_TbMntUnitaIntrv_TbArticoli] FOREIGN KEY ([IdArticolo]) REFERENCES [dbo].[TbArticoli] ([IdArticolo]),
    CONSTRAINT [FK_TbMntUnitaIntrv_TbMntAnagIntrvCausali] FOREIGN KEY ([IdCausaleIntrv]) REFERENCES [dbo].[TbMntAnagIntrvCausali] ([IdCausaleIntrv]),
    CONSTRAINT [FK_TbMntUnitaIntrv_TbMntManutentori] FOREIGN KEY ([IdManutentore]) REFERENCES [dbo].[TbMntManutentori] ([IdManutentore]),
    CONSTRAINT [FK_TbMntUnitaIntrv_TbMntUnita] FOREIGN KEY ([IdUnita]) REFERENCES [dbo].[TbMntUnita] ([IdUnita]),
    CONSTRAINT [FK_TbMntUnitaIntrv_TbMntUnitaIntrvPiani] FOREIGN KEY ([IdPiano]) REFERENCES [dbo].[TbMntUnitaIntrvPiani] ([IdPiano]),
    CONSTRAINT [FK_TbMntUnitaIntrv_TbOdlDet] FOREIGN KEY ([IdOdlDet]) REFERENCES [dbo].[TbOdlDet] ([IdOdlDet]),
    CONSTRAINT [FK_TbMntUnitaIntrv_TbProdCdlUnita] FOREIGN KEY ([IdCdlunita]) REFERENCES [dbo].[TbProdCdlUnita] ([IdCdlUnita]),
    CONSTRAINT [FK_TbMntUnitaIntrv_TbProdLotti] FOREIGN KEY ([IdProdLotto]) REFERENCES [dbo].[TbProdLotti] ([IdProdLotto]),
    CONSTRAINT [FK_TbMntUnitaIntrv_TbUtenti] FOREIGN KEY ([IdUtenteIntrv]) REFERENCES [dbo].[TbUtenti] ([IdUtente]),
    CONSTRAINT [FK_TbMntUnitaIntrv_TbUtenti1] FOREIGN KEY ([IdUtenteProd]) REFERENCES [dbo].[TbUtenti] ([IdUtente])
);


GO

